shallow_clone: true

version: '{build}'

os:
  - Visual Studio 2017
  - Visual Studio 2015

platform:
  - x64

configuration:
  - Release

build:
  verbosity: detailed

environment:
  CMAKE_INSTALL_PREFIX: C:\projects\KinectLibraries\install\

build_script:
  - mkdir build
  - mkdir install
  - cd build
  - cmake.exe .. -DCMAKE_INSTALL_PREFIX="C:\projects\KinectLibraries\install" -DDOWNLOAD_LibFreenect=ON -DBUILD_DOC=OFF -DCMAKE_BUILD_TYPE=%CONFIGURATION%  -DCMAKE_CONFIGURATION_TYPES=%CONFIGURATION% 
  - cmake.exe --build . --config %CONFIGURATION%
  - cmake.exe --build . --target install --config %CONFIGURATION%
