# Language selection
language: cpp

cache: ccache

# Environment variables:
matrix:
 include:
   #### linux
 - os: linux
   env: EXTRA_BUILD_FLAGS="-DDOWNLOAD_LibFreenect=ON -DBUILD_DOC=OFF" CC=gcc-5 CXX=g++-5

   ####  osx
 - os: osx
   env: EXTRA_BUILD_FLAGS="-DDOWNLOAD_LibFreenect=ON -DBUILD_DOC=OFF" CC=gcc CXX=g++

env:
  global:
  - BUILD_FLAGS="-DCMAKE_BUILD_TYPE=Release"


# Ubuntu 14.04 LTS (trusty)
dist: trusty

# No need for sudo
sudo: false

# Compilation dependencies
addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
    packages:
      - libusb-1.0-0-dev
      - freeglut3-dev
      - qtbase5-dev

# Actual compilation script

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
      brew update
      # seems to be needed on Travis due to conflicts with gcc otherwise
      # see https://github.com/travis-ci/travis-ci/issues/8826
      brew cask uninstall oclint
      brew install ccache
      export PATH="/usr/local/opt/ccache/libexec:$PATH"
      brew install libusb
      brew install freeglut
      brew install qt5
      
# Canonical path to qt5 directory
QT="/usr/local/Cellar/qt"
if [ ! -d "$QT" ]; then
    # Alternative (old) path to qt5 directory
    QT+="5"
    if [ ! -d "$QT" ]; then
        echo "Qt/Qt5 not found!"
        exit
    fi
fi
QT5_DIR="$QT/$(ls $QT | sort -r | head -n1)"
echo $QT5_DIR

# Change qt5 framework ids
for framework in $(find "$QT5_DIR/lib" -regex ".*/\(Qt[a-zA-Z]*\)\.framework/Versions/5/\1"); do
    echo "$framework"
    install_name_tool -id "$framework" "$framework"
done
    fi   
      
install:
  - mkdir build install
  - cd build
  - cmake $BUILD_FLAGS $EXTRA_BUILD_FLAGS -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/install ..

script:
  - make -j 2