# Language selection
language: cpp

cache: ccache

# Environment variables:
# To avoid too many builds, we mix some options (although independent tests would have been better)
matrix:
 include:
   #### linux
 - os: linux
   env: EXTRA_BUILD_FLAGS="-DDOWNLOAD_LibFreenect=ON -DBUILD_DOC=OFF" CC=gcc-5 CXX=g++-5

   ####  osx
 - os: osx
   python: 3
   env: EXTRA_BUILD_FLAGS="-DOWNLOAD_LibFreenect=1" CC=gcc CXX=g++

env:
  global:
  - BUILD_FLAGS="-DCMAKE_BUILD_TYPE=Release"


# Ubuntu 14.04 LTS (trusty)
dist: trusty

# No need for sudo
sudo: false

# Compilation dependencies
addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
    packages:
      - libusb-1.0-0-dev
      - freeglut3-dev
      - qtbase5-dev

# Actual compilation script

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
      brew update
      # seems to be needed on Travis due to conflicts with gcc otherwise
      # see https://github.com/travis-ci/travis-ci/issues/8826
      brew cask uninstall oclint
      brew install ccache
      export PATH="/usr/local/opt/ccache/libexec:$PATH"
      brew install libusb
      brew install freeglutW
      brew install qt5
    fi   
      
install:
  - mkdir build install
  - cd build
  - cmake $BUILD_FLAGS $EXTRA_BUILD_FLAGS -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/install ..

script:
  - make -j 2